# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import distlock_pb2 as distlock__pb2
import grpc

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in distlock_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class DistlockStub(object):
    """A distributed lock service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateLock = channel.unary_unary(
            "/distlock.Distlock/CreateLock",
            request_serializer=distlock__pb2.CreateLockRequest.SerializeToString,
            response_deserializer=distlock__pb2.EmptyResponse.FromString,
            _registered_method=True,
        )


class DistlockServicer(object):
    """A distributed lock service"""

    def CreateLock(self, request, context):
        """Creates a new lock on the server with the given name."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DistlockServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateLock": grpc.unary_unary_rpc_method_handler(
            servicer.CreateLock,
            request_deserializer=distlock__pb2.CreateLockRequest.FromString,
            response_serializer=distlock__pb2.EmptyResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "distlock.Distlock", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("distlock.Distlock", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Distlock(object):
    """A distributed lock service"""

    @staticmethod
    def CreateLock(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/distlock.Distlock/CreateLock",
            distlock__pb2.CreateLockRequest.SerializeToString,
            distlock__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
